#!/bin/sh
##########################################################################
# create the combined legacy outcome files with the filename appended as the last column
#
# LTS Computing LLC
##########################################################################

# process the first file - including adding "filename" column name to the header line at the start of the file
f="ascii/OUTC04Q1.TXT"
thefilenamenosuffix=$(basename "$f" .TXT)
# remove windows carriage return, fix bad data records with embedded \n, add on the "filename" column name to the header line and add the filename as the last column on each line
# output to the all data file
sed 's|\r||g' "$f" | sed "1 s|$|FILENAME|" | sed "2,\$ s|$|$f|" > all_outc_legacy_data_with_filename.txt

# process the other files and concatenate to the all data file
FILES="
ascii/OUTC04Q2.TXT  ascii/OUTC04Q3.TXT  ascii/OUTC04Q4.TXT  ascii/OUTC05Q1.TXT  ascii/OUTC05Q2.TXT  ascii/OUTC05Q3.TXT  ascii/OUTC05Q4.TXT  ascii/OUTC06Q1.TXT  ascii/OUTC06Q2.TXT  ascii/OUTC06Q3.TXT  ascii/OUTC06Q4.TXT  ascii/OUTC07Q1.TXT  ascii/OUTC07Q2.TXT
ascii/OUTC07Q3.TXT  ascii/OUTC07Q4.TXT  ascii/OUTC08Q1.TXT  ascii/OUTC08Q2.TXT  ascii/OUTC08Q3.TXT  ascii/OUTC08Q4.TXT  ascii/OUTC09Q1.TXT  ascii/OUTC09Q2.TXT  ascii/OUTC09Q3.TXT  ascii/OUTC09Q4.TXT  ascii/OUTC10Q1.TXT  ascii/OUTC10Q2.TXT  ascii/OUTC10Q3.TXT  ascii/OUTC10Q4.TXT
ascii/OUTC11Q1.TXT  ascii/OUTC11Q2.TXT  ascii/OUTC11Q3.TXT  ascii/OUTC11Q4.TXT  ascii/OUTC12Q1.TXT  ascii/OUTC12Q2.TXT  ascii/OUTC12Q3.TXT
"
for f in $FILES
do
        thefilenamenosuffix=$(basename "$f" .TXT)
        # remove windows carriage return,fix bad data records with embedded \n, remove the header line and add the filename as the last column on each line
        sed 's|\r||g' "$f" | sed '1d' | sed "s|$|$f|" >> all_outc_legacy_data_with_filename.txt
done
